services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
    networks:
      - app-network

  init-kafka:
    image: bitnami/kafka:latest
    networks:
      - app-network
    depends_on:
      - kafka
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "Waiting for Kafka to be ready..."
        sleep 15
        kafka-topics.sh --create --topic job-topic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1
        echo "job-topic created successfully. Keeping the container running for a while to ensure propagation."
        sleep 30

  notification-service:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5001
      - MongoDB__ConnectionString=null
    depends_on:
      - kafka
    networks:
      - app-network

  job-service:
    build:
      context: ./JobService
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5002
      - MongoDB__ConnectionString=null
    depends_on:
      - kafka
    networks:
      - app-network

  user-service:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - MongoDB__ConnectionString=null
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
